import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Youssef",
      email: "yooiialy@gmail.com",
      password: bcrypt.hashSync("yooiioo123@", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "john@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike slim Shirt",
      category: "Shirts",
      image: "/Img/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas fit Shirt",
      category: "Shirts",
      image: "/Img/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Lacoste free Shirt",
      category: "Shirts",
      image: "/Img/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Nike slim Pant",
      category: "Pants",
      image: "/Img/p4.jpg",
      price: 130,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Puma slim Pant",
      category: "Pants",
      image: "/Img/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Pant",
      category: "Shirts",
      image: "/Img/p6.jpg",
      price: 240,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
